trigger:
  batch: true
  branches:
    include:
    - master
    - repro
pr:
  branches:
    include:
    - master
    - repro
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Start-Sleep -s 180
